server:
  port: 8085
  context-path: /

security:
  sessions: if-required
  #ALWAYS
  #user.password: password
  #if-required
  #encrpyt.encoder bcrypt or SHA-256,default:SHA-256
  encrypt.encoder: SHA-256
  encrypt.hash-interations: 1024
  encrypt.strength: 8
  # ALWAYS
  oauth2:
    resource:
      resourceId: party-build-4a-userinfo
      userInfoUri: http://localhost:9999/sso/user/principal
    server:
      checkTokenUri: http://localhost:9999/sso/oauth/check_token
      resourceId: party-build-4a-userinfo
      resourceSecret: ido85R&Dcenter
      
  
spring:
  application:
    name: party-build-4a-userinfo
  datasource:
    dataSourceClassName: com.highgo.jdbc.jdbc2.optional.SimpleDataSource
    url: jdbc:highgo://192.168.10.211:5866/sso_vpn_copy?useUnicode=true&characterEncoding=utf-8
    username: highgo
    password: highgo85ido
    poolName: StringBootHikariCP
    maximumPoolSize: 5
    minimumIdle: 3
    maxLifetime: 2000000
    connectionTimeout: 30000
    idleTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 300
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  redis:
    host: 192.168.10.230
    #host: localhost
    password: ido85redis
    port: 6379
    database: 10
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    cache: false
    excluded-view-names: 
    check-template-location: true
    mode: LEGACYHTML5
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.230:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level: debug
#    org.springframework.security: INFO
#    org.springframework.data.ldap: debug